remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
title: Leak, Cheat, Repeat - Data Contamination and Evaluation Malpractices in Closed-Source LLMs
description: The website accompanying the EACL 2024 paper "Leak, Cheat, Repeat - Data Contamination and Evaluation Malpractices in Closed-Source LLMs"
show_downloads: false
