theme: jekyll-theme-minimal
title: Leak, Cheat, Repeat: Data Contamination and Evaluation Malpractices in Closed-Source LLMs
description: The website accompanying the EACL 2024 paper "Leak, Cheat, Repeat: Data Contamination and Evaluation Malpractices in Closed-Source LLMs"

